#!/usr/bin/env php
<?php
require_once(__DIR__ . '/vendor/autoload.php');

use Gin\Downloader\DownloaderApplication;

$application = new DownloaderApplication("PHP Youtube Downloader", "0.9", __DIR__, basename(__FILE__));
$application->run();
